---
test stretch:
  image: debian:stretch
  script: debian/run-ci

test buster:
  image: debian:buster
  script: debian/run-ci

flake8:
  image: debian:9
  script:
    - apt-get update
    - apt-get install -y flake8
    - flake8
  allow_failure: true
